version: '2.1'

services:
  webapp:
    image: java:8
    volumes:
      - ~/.gradle/:/root/.gradle
      - ./:/app/bidmeister/
    ports:
      - 8080:8080
    links:
      - elasticsearch
      - mongodb
    networks:
      - backend
    command: /app/bidmeister/gradlew -b /app/bidmeister/build.gradle bootRun
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - backend
  elasticsearch:
    image: elasticsearch:2.0.0
    ports:
      - 9200:9200
    networks:
      - backend

networks:
  backend:
    driver: bridge
